### PR TITLE
add 2 TBD glossaries

### PR DESCRIPTION
**Pull request by anilbey**
- add TBD 2013 cayfer-bilkent.csv. Manually converted from http://cayfer.bilkent.edu.tr/~cayfer/bilisim-sozlugu/tbd-ing-trk-sozluk.htm
- add TBD 2022-04-25 pdf glossary (To be converted to .csv)

### CODE REVIEW

**Comment by anilbey** [comment]
Hi @BatoolMM can you give me write access please?

**Comment by BatoolMM** [comment]
Hi @anilbey you have write access to this repository, now? Let me know if you need anything else!

**Review by BatoolMM — APPROVED** [review]

**Comment by BatoolMM** [comment]
It might be better to have the column names (1st row = İNGİLİZCE,TÜRKÇE) in English?

**Comment by anilbey** [comment]
@BatoolMM  thanks, I updated it to be ENGLISH,TURKISH

**Pull request merged**
